// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWVFPgeXCiFaaHeYNlivP53JuXden-FfM',
    appId: '1:1078104509754:web:e896596a19b07609d75403',
    messagingSenderId: '1078104509754',
    projectId: 'flutter-firebase-a2z',
    authDomain: 'flutter-firebase-a2z.firebaseapp.com',
    storageBucket: 'flutter-firebase-a2z.appspot.com',
    measurementId: 'G-JP8RQVX78P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoEQsV8XlLLBKIJUSaE00Hdp28Bu1Bak8',
    appId: '1:1078104509754:android:2ca164fc7db1ff50d75403',
    messagingSenderId: '1078104509754',
    projectId: 'flutter-firebase-a2z',
    storageBucket: 'flutter-firebase-a2z.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvs1t3kJvUBSaSLeZv3eb83zMIJFvNQM8',
    appId: '1:1078104509754:ios:5248a99e95ac32e8d75403',
    messagingSenderId: '1078104509754',
    projectId: 'flutter-firebase-a2z',
    storageBucket: 'flutter-firebase-a2z.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseA2z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvs1t3kJvUBSaSLeZv3eb83zMIJFvNQM8',
    appId: '1:1078104509754:ios:8e284b75a676d046d75403',
    messagingSenderId: '1078104509754',
    projectId: 'flutter-firebase-a2z',
    storageBucket: 'flutter-firebase-a2z.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseA2z.RunnerTests',
  );
}
